org: tbehunin
app: polzee-sls
service: polzee-sls

custom:
  stage: "${opt:stage, self:provider.stage}"
  myTable: "${self:custom.stage}-MyTable"
  dbPolls: "${self:custom.stage}-polls"
  dynamodb:
    # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    # Uncomment only if you already have a DynamoDB running locally
    # noStart: true

provider:
  name: aws
  runtime: nodejs8.10

  stage: dev
  region: us-west-2
  environment: ${file(env.yml):${self:custom.stage}}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:putitem
        - dynamodb:getitem
      Resource:
        - Fn::GetAtt: [MyTableRsrc, Arn]
        - Fn::GetAtt: [DbPollsRsrc, Arn]

plugins:
  - serverless-dynamodb-local
  - serverless-offline

functions:
  lambdaArgs:
    handler: functions/lambdaArgs.handler
    events:
      - http:
          path: lambdaArgs
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref PolzeeApiGatewayAuthorizer
  graphql:
    handler: functions/graphql.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref PolzeeApiGatewayAuthorizer
      - http:
          path: graphql
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref PolzeeApiGatewayAuthorizer

resources:
  - ${file(resources/dynamodb.yml)}
  - ${file(resources/s3-bucket.yml)}
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
  - ${file(resources/api-gateway.yml)}
