org: tbehunin
app: polzee-sls
service: polzee-sls

custom:
  stage: "${opt:stage, self:provider.stage}"
  myTable: "${self:custom.stage}-MyTable"

provider:
  name: aws
  runtime: nodejs8.10

  stage: dev
  region: us-west-2
  environment: ${file(env.yml):${self:custom.stage}}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:putitem
      Resource:
        Fn::GetAtt:
          - MyTableRsrc
          - Arn

plugins:
  - serverless-dynamodb-local
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: users/create
          method: get
  lambdaArgs:
    handler: handler.lambdaArgs
    events:
      - http:
          path: lambdaArgs
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref PolzeeApiGatewayAuthorizer
  graphql:
    handler: handler.graphql
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

resources:
  - ${file(resources/dynamodb.yml)}
  - ${file(resources/s3-bucket.yml)}
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
  - ${file(resources/api-gateway.yml)}
