service: polzee-sls

custom:
  stage: "${opt:stage, self:provider.stage}"
  myTable: "${self:custom.stage}-MyTable"

provider:
  name: aws
  runtime: nodejs8.10

  stage: dev
  region: us-west-2
  environment: ${file(env.yml):${self:custom.stage}}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:putitem
      Resource:
        Fn::GetAtt:
          - MyTableRsrc
          - Arn

plugins:
  - serverless-dynamodb-local
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: users/create
          method: get

resources:
  - ${file(resources/dynamodb.yml)}
  - ${file(resources/cognito-user-pool.yml)}
