org: tbehunin
app: polzee-sls
service: polzee-sls

custom:
  stage: "${opt:stage, self:provider.stage}"
  dbPolls: "${self:custom.stage}-polls"
  s3PollsBucket: "${self:custom.stage}-polls-bucket"
  dynamodb:
    # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    # Uncomment only if you already have a DynamoDB running locally
    # noStart: true
    seed:
      common:
        sources:
          - table: ${self:custom.dbPolls}
            sources:
              [
                ./data/seed/polls.json,
                ./data/seed/users.json,
                ./data/seed/directPolls.json,
                ./data/seed/votes.json,
                ./data/seed/follows.json,
                ./data/seed/comments.json,
                ./data/seed/likes.json,
              ]

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-west-2
  environment: ${file(env.yml):${self:custom.stage}}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:putitem
        - dynamodb:getitem
        - dynamodb:batchgetitem
        - dynamodb:query
      Resource:
        - Fn::GetAtt: [DbPollsRsrc, Arn]

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-dynamodb-local
  - serverless-offline

functions:
  lambdaArgs:
    handler: functions/lambdaArgs.handler
    events:
      - http:
          path: lambdaArgs
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref PolzeeApiGatewayAuthorizer
  graphql:
    handler: functions/graphql/index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref PolzeeApiGatewayAuthorizer
      - http:
          path: graphql
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref PolzeeApiGatewayAuthorizer

resources:
  - ${file(resources/dynamodb.yml)}
  - ${file(resources/s3-bucket.yml)}
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
  - ${file(resources/api-gateway.yml)}
