Resources:
  DbPollsRsrc:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.dbPolls}
      AttributeDefinitions:
        - AttributeName: hashKey
          AttributeType: S
        - AttributeName: sortKey
          AttributeType: S
        - AttributeName: scope
          AttributeType: S
        # - AttributeName: sharedPoll
        #   AttributeType: N
      KeySchema:
        - AttributeName: hashKey
          KeyType: HASH
        - AttributeName: sortKey
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: PollsHashKeyScopeIdx
          KeySchema:
            - AttributeName: hashKey
              KeyType: HASH
            - AttributeName: scope
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
