Resources:
  MyTableRsrc:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.myTable}
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      AttributeDefinitions:
        - AttributeName: "MyId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "MyId"
          KeyType: "HASH"