Resources:
  PolzeeAttachmentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      # Set the CORS policy
      BucketName: ${self:custom.s3PollsBucket}
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000

# Print out the name of the bucket that is created
Outputs:
  AttachmentsBucketName:
    Value:
      Ref: PolzeeAttachmentsBucket
